spring:
    application:
        name: ai-springai-RAG
    ai:
        dashscope:
            chat:
                options:
                    model: qwen3-max #?????
            api-key: sk-c1567448faf147e8b2ec11624b1cbe6c
            embedding:
              options:
                  model: text-embedding-v4  # ?????Embedding??
        vectorstore:
          milvus:
              client:
                host: 127.0.0.1
                port: 19530
              database-name: "default"
              embedding-dimension: 1024 #?????????? embedding ????????
              collection-name: "vector_store"    # ????
                # ?????????ivf_flat, ivf_sq8, ivf_pq, hnsw, diskann, flat
                # ivf_flat: ?????????????????????
                # ivf_sq8: ??????????????????????
              # ivf_pq: ?????????????????????????
              # hnsw: ???????????????????????
              # diskann: ??ANN????????????
              # flat: ????????????????????

              index-type: ivf_flat

                # ?????????l2, ip, cosine
                # l2: ???????????????????
              # ip: ????????????
              # cosine: ???????????????
              metric-type: cosine
              initialize-schema: true # ?????? schema?Milvus??????????????????????????
